thedaviddias/Front-End-Checklist

- README.md
Sorry, this must be a bit annoying.
> Fix Misspellings of 'repercussions' and 'dysfunction'

- README.md
Sometimes the items were formatted like 
**this**:
**this:**
**this:**:
I made them all look like **this:**
> Make colons consistently bold

- README.md
> Fix some tiny typos in README.md

- README.md
Adds a link to RealFaviconGenerator in addition to Favicon Generator. RealFaviconGenerator provides favicons and detailed information for various platforms.
> Add alternative favicon generator

- README.md
This fixes 2 small mistakes in the browsers testing recommendations.
Thanks for the checklist!
> Change "Desktop Mobile" to "Mobile Browsers", add S to browsers

- README.md
> Change MO to MB

- README.md
Change name to "Bootstrap" and use v4 link to reboot.
Also, trim trailing whitespace.
> Bootstrap updates.

- README.md
Hi,
Please accept my modest contribution to your project. I found your work so interesting and I wanted to help out. I corrected a few minor grammatical omissions, especially in the use of prepositions.
> minor grammar and spelling corrections

- README.md
Hi David,
I added a few options in regards to security of websites. This is mainly targeting HTTP headers. With the URLs to scanning services one would be able to tweak and improve their site(s) easily.
Regards, JoKi
> Add a few security-related entries

- README.md
* Add Observatory by Mozilla
* Remove duplicate backticks being used for inline code
* Use reference images to reduce duplication
> Assorted tweaks

- README.md
added link to Google Robots Testing Tool
> added google robots testing tool

- README.md
I've added a couple of useful links for sitemaps (an automatic generator, and some documentation provided by Google).
> added useful links for sitemaps

- README.md
> Fix some typos, grammar and formatting issues

- README.md
Add two missing [medium_img] images.
> Add missing images

- README.md
While on the topic of removing unused code, Chrome Devtools' code coverage feature is worthy of a mention.
> performance - code coverage from chrome dev tools

- README.md
I have been translated into Vietnamese. Please review and merge pull request if no matter what. 🚀 
You can see it here: https://github.com/euclid1990/Front-End-Checklist
> Add Vietnamese version

- README.md
I think that it would be better to be listed all the resources.
Also I added 📖  to following.
* Minify Resources (HTML, CSS, and JavaScript)
* Guidelines for Developing Secure Applications Utilizing JavaScript
Anyway, Is the `*` intentional?
Thanks 😊
> Add bullets to all resources

- README.md
Is this `*` intentional?
Thanks 😊
> Remove asterisk

- README.md
#88 This is my suggested wording (feel free to edit)
> amended image width and height suggestion

- README.md
I figured MDN was the best reference.
https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#Adding_an_author_and_description
> Added more-info URL for meta description per #3

- README.md
Hello,
I continue adding points from my performance checklist with the recommendation to use static components instead of iframes or components relying on external websites when possible.
I've set a medium level of flexibility on this one, as it can have an important impact on performance but depends on the kind of component you want to use.
> Recommend static components instead of iframes

- README.md
Changed the section to make it less dependent on the Critical library and stand more as its own concept.
> Made critical CSS section more independent

- README.md
Hello!
I hope it is a good idea to add a code guide for this article.
Currently I work on a Russian version of it. 
Cheers.
> feat: codeguide added to CSS note

- README.md
@thedaviddias 
Here is Traditional Chinese version.
Thanks for share awesome checklist.
> update Traditional Chinese translate link

- README.md
> Add `.` to the end of sentence and markup to html arguments.

- README.md
1. Add Kraken.io as an alternative tool to optimize;
2. Add about aria roles categorization;
3. Add Google considerations about web fonts.
> Add about aria roles, webfonts and image optim

- README.md
[GTmetrix](https://gtmetrix.com/) is a website where you can analyze:
* The speed of your page with Google's algorithm (PageSpeed)
* The speed of your page with Yahoo's algorithm (YSlow)
* The evolution of your page speed
You can also get good advices about optimization and watch a video where you can see how your web loads.
I have used this resource since more than three years ago and I think that it's one of the most completed.
> Add GTmetrix

- README.md
Hi,
My little contribution to the community : Sonarwhal a linting tool for the web
> Added useful link

- README.md
I added CSP to the Security section with some resources that provide good information on it. It is a powerful tool for front-end security and should be included in the checklist. Thanks!
> Add Content Security Policy to Security Section

- README.md
Just fixing a pet peeve of mine
> GitHub has a capital H

- README.md
Sorry, it is really small fix. 😊
> Fix missing dot.

- README.md
Add 3 links about structured data and semantic markup to helps on SEO.
> Add more 3 links about SEO

- README.md
I noticed that a few list items have no level marks. So I added.
> Add flexibility levels to some items

- README.md
Contribution link failed to jump
> Contributors link failed to jump

- README.md
**Fixes**: #61 
Adds link tags for paginated content
> Add pagination link tags

- README.md
Adding support for the iPhone X viewport.
[Suggested in Issue #160](https://github.com/thedaviddias/Front-End-Checklist/issues/160)
[Original Article](https://webkit.org/blog/7929/designing-websites-for-iphone-x/)
`<meta name='viewport' content='initial-scale=1, viewport-fit=cover’>`
It's better to change to
`<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">`
👍 Thank you!
> add iPhone X viewport support

- README.md
**Fixes**: #
- [x ] Check the commit's or even all commits' message styles matches our requested structure.
- [x ] Check your code additions will fail neither code linting checks nor unit test.
Only one paragraph has been translated. But It's completely ready on the other fork. At least that link should not be here until the end of the translation.
- unfinished turkish translation removed.
-
-
👍 Thank you!
> unfinished translation removed .

- README.md
- Fix typos
- Improve `Apple Meta Tags` checklist item
> Fix typos, improve Apple Meta Tags checklist item

- README.md
+> * 🛠 [TinyPNG](https://tinypng.com/) losslessly optimise png, apng (animated png) and jpg images. Free and paid version available.
+> * 🛠 [ZorroSVG](http://quasimondo.com/ZorroSVG/) jpg-like compression for transparent images using svg masking.
+> * 🛠 [SVGO](https://github.com/svg/svgo) a Nodejs-based tool for optimizing SVG vector graphics files. 
+> * 🛠 [SVGOMG](https://jakearchibald.github.io/svgomg/) a web-based GUI version of SVGO for optimising your svgs online.
>  Additions to image optimization section

- README.md
**Fixes**: #
Purifycss does not seem to be maintained anymore. Purgecss is a similar tool with a few improvements and features.
- Add [Purgecss](https://github.com/FullHuman/purgecss) to the list of tools to remove unused css
👍 Thank you!
> add purgecss

- README.md
**Fixes**: #95
This PR replaces the 500KB page size goal by the goals advised in [Smashing Magazine's performance checklist](https://www.smashingmagazine.com/2018/01/front-end-performance-checklist-2018-pdf-pages/).
- Replace the 500KB page size goal by the goals described in #95 from Smashing Magazine's performance checklist
- Change `high` by `medium` as these goals are not so easy to reach for everyone
> Add performance goals

- src/scripts/components/Dropdown.js
Clicking on the expand button more than once generated multiple code blocks. I added a conditional check.
> Fixed dropdown

- data/en/items/accessibility.json
**Fixes**: #
-
-
-
👍 Thank you!
> Accessibility - screen reader update #257

- README_APP.md
Great project; thanks!
**Fixes**: #
Duplicate index entry, broken add-new-translation entry
- Minor change to TOC
👍 Thank you!
> Fix TOC entries in README_APP.md

- src/styles/base/_print.scss
**Fixes**: #254
Do not print the footer URL.
> Fix printing report shows the footer URL

- package.json
Reverts thedaviddias/Front-End-Checklist#282
> Revert "Update babel-loader to the latest version 🚀"

- gulpfile.babel.js
Starting to bring the `gulpfile` style up to match your eslint settings. I tried to avoid any of the polarizing ones (e.g. comma dangle in function parameters), so I just did some basic formatting and wanted to check before I went too far.
> Fix some eslint errors in the gulpfile

- README.md
**Fixes**: #
ASafaWeb is not working anymore, so this PR is to remove the link.
- I removed the link from README.md.
👍 Thank you!
> docs(security): remove asafaweb link

- package.json
**Fixes**: #
When rurnning `gulp dev --l ar` I had `Cannot find module 'del'` error:
```
[00:56:07] Failed to load external module @babel/register
[00:56:07] Requiring external module babel-register
module.js:549
throw err;
^
Error: Cannot find module 'del'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
```
- Added [del](https://github.com/sindresorhus/del) to package.json
👍 Thank you!
> Add del to package.json

- src/scripts/components/Storage.js
**Fixes**: #327 
- check for duplicates before adding to storage
This can fix other potential issues down the line.
> Check for duplicate items before adding to storage

- .gitpod.yml
- README.md
Hi! there :slightly_smiling_face: .
This PR simplifies code contributions by adding configuration for gitpod (A Free online VS Code like Ide). With a single click, it will launch a ready to code workspace with all the dependencies being pre-installed & the start & build scripts in process so that anyone interested in contributing can start coding straight away without wasting any time on dev setup.
You can give it a try on My Fork of the repo:
https://gitpod.io/#https://github.com/nisarhassan12/Front-End-Checklist
> simplified code contributions by automating the dev setup with gitpod.

- README.md
Added another link for image optimization.
**Fixes**: #
-
-
-
👍 Thank you!
> Added KeyCDN Image Processing for image optimization

- README.md
> fixes #379 : fix the broken gitpod button link.

- package-lock.json
- src/scripts/components/Report.js
- [ x] Check the commit's or even all commits' message styles matches our requested structure.
- [ x] Check your code additions will fail neither code linting checks nor unit test.
As per [spec](https://html.spec.whatwg.org/multipage/webstorage.html#the-storage-interface), ```localstorage``` uses Storage object interface, so the check for a null value is wrong and it generates an error when clearing data with the button "Start new checklist".
- Bugfix localstorage values check
👍 Thank you!
> Bugfix localstorage values check

- README.md
**Fixes**: #
-
-
-
👍 Thank you!
> Suggestion to fix the broken links from OWASP cheatsheets

- .dependabot/.config.yml
> feat: add dependabot config

- README.md
**Fixes**: #
For better homogeneity of markdown syntax, I replaced dashes symbol used in minority for list items by stars.
- Replace dashes symbol by stars as list item symbol 
👍 Thank you!
> Use only star as list item symbol

- README.md
Tools added to check whether the website is Responsive under the Responsive web design section.
**Fixes**: #
-Tools Added for checking Responsiveness of the website. 
👍 Thank you!
> Tools for checking Responsiveness of the website.

- README.md
As this is a simple self-explaining "adding my library" docs change, I haven't opened a separate issue for it.
> docs(lazyloading): added polyfill to that section

- README.md
Added link to Polish version.
**Fixes**: #
- [x ] Check the commit's or even all commits' message styles matches our requested structure.
- [x ] Check your code additions will fail neither code linting checks nor unit test.
Added link to Polish translation.
https://github.com/mbiesiad/Front-End-Checklist
👍 Thank you!
Best wishes,
> Add Polish

- README.md
**Fixes**: #
-
-
-
👍 Thank you!
> added google search console in SEO section

- README.md
Google Structured Data Test tool is deprecated, sunsetting soon. Alternative is Google's Rich Results Test tool https://search.google.com/test/rich-results
- Update the link to new Rich Results Test tool
👍 Thank you!
> Updated structured data test tool

- README.md
Hi, I've just made the new pull request as you suggested. 
- Add Indonesian Translation 
👍 Thank you!
> Indonesian Translation

- README.md
**Fixes**: #
Update broken link of `aria-label`
-
-
-
👍 Thank you!
> Update Broken link

- README.md
On the site, it says that the compression is lossy, not lossless.
> Noted TinyPNG isn't lossless

- README.md
Fixes #486
Adds SVG favicon as another recommended alternative in the README.md, warning not to use it when targeting old browsers
- self-explanatory
👍 Thank you!
> add SVG to favicon options
