thedaviddias/Front-End-Checklist

- README.md
Great checklist! Also changed the Page Weight tool to a more user friendly and less ad covered tool.
Also wondering in the Font Sections it mentions ```2 MO``` is this meant to be ```2 MB``` or something else? A quick google search gave me nothing about MO so a little explanation would be great!
> Fixed typos with Weight Page section

- README.md
This way it's consistent with other HTML tags and also improves compression (Bootstrap is also using it this way).
> Use a lowercase doctype

- README.md
Hello,
Small fix, the link from the Table of Contents to Performance section actually leads to CSS' performance section. This commit fixes this.
> Fix link from Table of Contents to Performance

- README.md
Hello,
I've created [this checklist](https://github.com/antarestupin/performance-checklist) focused on performance recently and I'd like to share some practices that I don't see yet in this list.
I wanted to begin with techniques allowing to prepare upcoming requests during browser's idle time, so I'm adapting [this section](https://github.com/antarestupin/performance-checklist#prepare-next-requests) to the format used here.
I've created a sub-section in `Performance`, but I'm not sure of where this section should be placed as there are performance related practices spread over all the list, so it's open to discussion. Same for the levels of flexibility.
> Add prefetching techniques in performance section

- README.md
A pipe is often used for a table. Github could handle it fine but the rendering on webpage was adding a table in the middle of a link
> Remove pipe from MDN page links

- README.md
Describes minimum needed to enable tiles for pinned sites on Windows through Microsoft browsers.
Read more @ [Browser configuration schema reference](https://msdn.microsoft.com/en-us/library/dn320426(v=vs.85).aspx)
> Added Microsoft's browser configuration scheme

- README.md
Meta title in Google search result has pixel width limits and not character count limits.
> updated SEO info about Ttile

- README.md
The description for Error pages referred to 5xx error pages as `his` when in fact they have no gender.
> Update README.md to not assume gender 🙂

- README.md
I confused what width and height are meaning during I was translating this cool documentation.
I think attributes should be written like \`width`.
Thanks 😊
> improve to display atts

- README.md
It is more logical to put _Pixel Perfect_/ _Desktop and Mobile browser_ tests to CSS Testing instead on HTML Testing. 
Because this concern visual testings, HTML will be the same across browser, CSS is not so sure...
Also add a _OS testing_ to test the CSS in different OS. A lot of CSS issues can appear on Mac or iOS comparing to Windows...
Last is adding a recommended practice by using picture/srcset. This is becoming a standard to load different images on mobile and desktop. I guess it can include the Retina part too. Medium seems to be the right priority.
> Move some HTML testing to CSS Testing + Add picture/srcset best practice

- README.md
As the limit for the title char count depends on the rendered Google SERP it's useful to check it in a tool like this.
> add serp generator tool to title section

- README.md
Using a webfont loader to ensure your users don't get a FOUT/FOIT is a great idea.
> Add note about webfonts and webfont loaders

- README.md
Providing these options ensures that the share image is immediately rendered in preview every time, without it the first time there will be no image preview until Facebook has crawled the site once - particularly useful if you have generated share images.
> Adding Facebook image sharing height and width.

- README.md
This will be useful when using client-side rendering heavy apps such as React, Vue etc and scripts are disabled on the page
> Add `noscript` tag to JavaScript best practices

- package.json
- src/styles/components/_c-nav.scss
**Fixes**: #
Prevents repainting while scrolling by pomoting the sidebar to its own compositor layer.
Promotes the sidebar to its own layer by using `will-change: transform`
👍 Thank you!
> Promote sidebar to its own layer

- package.json
- src/styles/components/_c-nav.scss
The package name contains uppercase characters, which aren't allowed in a valid `package.json` file:
```
String does not match the pattern of "^(?:@[a-z0-9-~][a-z0-9-._~]*/)?[a-z0-9-~][a-z0-9-._~]*$".
```
Changed name to `front-end-checklist`
> Package name fix — remove uppercase characters

- README.md
**Fixes**: #188
- [x ] Check the commit's or even all commits' message styles matches our requested structure.
- [x ] Check your code additions will fail neither code linting checks nor unit test.
The purpose of <!doctype html> is to ensure standards compliant rendering, avoiding quirks mode, even in older browsers.  To fulfill this purpose, it must be the first item in the file. 
Older IE browsers will trigger quirks mode instead of standards mode if <!doctype html> is not at the very beginning of the document.
https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode
"Make sure you put the DOCTYPE right at the beginning of your HTML document. Anything …
> Comment should not precede DOCTYPE

- README.md
Translations section must be at the top of this document.
I was disappointed when I read all the readme in English and only at the end of this file I find out that a translation in my native language (Portuguese) exists, after suffering...
> Moved translations section to the top

- README.md
**Fixes**: #
The link to CONTRIBUTING.md in the README.md is not correct as the file is in the .github folder.
- fix the link
👍 Thank you!
> fix link to contributing.md

- README.md
**Fixes**: N/A
Changes a small piece of literature in [`README.md`](https://github.com/thedaviddias/Front-End-Checklist/blob/8686dd6d17c14985e1f7619288acd418f3d3eafd/README.md) due to `X-UA-Compatible` being deprecated in IE11, this slipped through 8686dd6.
- N/A
👍 Thank you!
> Remove leftover reference to X-UA Compatible

- README.md
HTTPS is one of the most important things on the internet today. There is no legitimate reason that websites shouldn't be using HTTPS, especially with tools such as Let's Encrypt. Especially with Google Chrome's recent change to mark HTTP sites as "Not Secure" HTTPS is more important than ever, and there is no reason that websites shouldn't be using it. Therefor I believe HTTPS should be considered high priority instead of medium.
Below are a few links to resources about why HTTPS is important:
- https://security.googleblog.com/2016/09/moving-towards-more-secure-web.html
- https://www.troyhunt.com/heres-why-your-static-website-needs-https/
- https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https
- https://mashable.com/2011/05/31/https-web-security/#u5TLPUa2x5q …
> Setting HTTPS to High Priority

- README.md
- The link went to an empty site, now it refers to the actual site. This shouldn't mess with any tests or guidelines, as I only changed the address. Still read the guidelines and I think this is fine.
Possibly outdated link on the README changed for actual link
👍 You're welcome :)
> Corrected Link in README

- src/views/components/checklist/dropdown.pug
I think we should have had dropdowns if videos available.
They should reveal links to these videos.
I was expecting this:
Instead, on frontendchecklist.io, we see the below with no dropdown:
> Expand if item has videos

- README.md
**Fixes**: #
The link for Dirty Markup pointed to a redirect URL whose cert has been invalid for 3 three months.
- Change the link to go to the page that we were being redirected to anyway so the invalid cert doesn't stop/confuse people
👍 Thank you!
> Fix the link for Dirty Markup

- .gitpod.yml
- README.md
Hi! :slightly_smiling_face: 
This PR enhances the Gitpod setup by removing the build task to make the server start fast and it also makes its description precise in the `README.md`
> [gitpod-setup] remove the build task to make the server startup fast + make the description more precise. 

- data/en/items/webfonts.json
**Fixes**: #
- [ X] Check the commit's or even all commits' message styles matches our requested structure.
- [ X] Check your code additions will fail neither code linting checks nor unit test.
Currently in the checklist, the Webfont size check states the total size of the webfonts must not exceed 2 MB. I see two problems with this:
1. this is very much in conflict with the check "Page weight" which communicates an total max page weight of 500 KB
2. Loading 2 MB of fonts onto a page would hurt page speed/performance significantly
Change the …
> Lower upper limit of the web fonts payload

- README.md
As discussed by others in #405, there's no good reason for Google Analytics being in a category where it:
> can't be omitted by any reason.
To add on to what others have said, this statement above is also misleading. There shouldn't be a requirement to fork over user data to Google as part of all, or even most, front end development.
Fixes #405
> Decrease Google Analytics importance to Low

- README.md
I have deleted this link from the SEO section of the readme.md page because this link - https://rdfa.info/  doesn't have valid ssl or tls and doesn't abide by the basic security measures which pose a potential threat to the users and moreover the webpage is not accessible because the browser doesn't allow these kind of pages to be displayed.
**Fixes**: #
-Deleted RDFa - Linked Data in HTML from SEO section of readme.md other than that everything is left untouched.
👍 Thank you!
> Deleting RDFa - Linked Data in HTML

- README.md
**Fixes**: #
Issue #441 
Corrected the broken URL to point to https://developer.chrome.com/docs/devtools/coverage/ 
mods, please verify if newly added url is indeed what we are looking for.
👍 Thank you!
> Issue #441: Fixed the broken link.

- README.md
Remove pagination from SEO section, because it's not an SEO index anymore and google has removed the related docs, see [here](https://twitter.com/googlesearchc/status/1108726443251519489?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1108726443251519489%7Ctwgr%5E%7Ctwcon%5Es1_c10&ref_url=https%3A%2F%2Ftechnicalseo.com%2Ftools%2Frel-prev-next%2F).
> Remove pagination from SEO section

- CONTRIBUTING.md
The "How to Contribute to an Open Source Project on Github" link returns a 404.
I've updated it with a working link.
> update outdated link

- README.md
Grammatical error in the line mentioned  
All items in the **Front-End Checklist** are required for the majority of the projects, but some elements can be omitted or are not essential (in the case of an administration web app, you may not need RSS feed for example). We choose to use 3 levels of flexibility:
All items in the Front-End Checklist are necessary for the majority of projects, but some elements can be omitted or are not essential. For example, in an administration web app, you may not need an RSS feed. We have categorized the flexibility into three levels:
> my-contribution into the readmefile
